version: '3.8'

services:
  # 1. ArangoDB Database Service
  arangodb:
    image: arangodb:latest
    container_name: nuptial_arangodb
    restart: unless-stopped
    environment:
      # The password is read from the .env file in the project root
      - ARANGO_ROOT_PASSWORD=825c3586b5c09ec3823b4a8e586e9004
    ports:
      - "8530:8529"
    volumes:
      # Persist data on the host machine in the 'arangodb_data' directory
      - ./arangodb_data:/var/lib/arangodb3
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8529/_api/version"]
        interval: 30s
        timeout: 10s
        retries: 5

  # 2. CORS Proxy Service
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: nuptial_cors_proxy
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - arangodb

  # 3. Map Tile Server Service
  tileserver:
    image: klokantech/tileserver-gl:latest
    container_name: nuptial_tileserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      # Mount the local 'tiles' directory to serve .mbtiles files
      - ./tiles:/data

networks:
  default:
    name: nuptial-network 